In [1]:
import numpy as np

In [3]:
a=np.array([[1,0],[0,1]])
a

array([[1, 0],
       [0, 1]])

In [5]:
b=np.array([[2,1],[1,2]])
b

array([[2, 1],
       [1, 2]])

In [7]:
c=np.dot(a,b)
c

array([[2, 1],
       [1, 2]])

In [8]:
t=b.transpose()
t

array([[2, 1],
       [1, 2]])